name: CD

on:
    workflow_call:
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Executing remote ssh commands using password
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }} 
                port: 22
                script: |
                    echo "Stating Deployment"
                    docker compose down
                    docker compose pull
                    sleep 5
                    docker compose up -d