name: DevSecOps End To End Pipeline

on:
    push:
        branches: [main]
jobs:
    # Security scan
    code_quality_check:
        uses: ./.github/workflows/code-quality.yml

    sectet_scan:
        uses: ./.github/workflows/seceret-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependencies.yml
    
    docker_scan:
        uses: ./.github/workflows/docker-lint.yml
    
    #building docker image
    build_docker:
        needs: [code_quality_check, sectet_scan, dependency-scan, docker_scan]
        uses: ./.github/workflows/docker-buld-push.yml
        secrets: inherit

    trivy_scan:
        needs: [build_docker]
        uses: ./.github/workflows/docker-image-scan.yml
        secrets: inherit
    
    