
name: docker-linter

on:
    workflow_call:
        
jobs:
    docker-lint-image-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            

            - name: validate Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile